### PR TITLE
Merge kedacore/keda-olm-operator:main into main

### PR DESCRIPTION
**Pull request by joelsmith**
After fetching `kedacore/keda-olm-operator:main` and trimming it back to 2.8.2 and pushing it to  `joelsmith/keda-olm-operator:kedamain`, I ran the following:

```
rebasebot --source https://github.com/joelsmith/keda-olm-operator:kedamain \
    --dest openshift/custom-metrics-autoscaler-operator:main \
    --rebase joelsmith/keda-olm-operator:rebase-bot-main \
    --github-user-token <(yaml2json ~/.config/hub | jq -r '."github.com"[0].oauth_token') \
    --update-go-modules \
    --exclude-commits 5d10a6db28a864d519f255d80411979eee65d94c 902f6bcbf722004222b578a6f20a1099127771fb
```

additionally added a cherry-pick of https://github.com/kedacore/keda-olm-operator/pull/173

### CODE REVIEW

**Review by zroubalik — COMMENTED** [review]
audit log feature is missing, is that intentional? https://github.com/kedacore/keda-olm-operator/commit/1f91a80bc8d54206a23c5ffc9fb6b9457abff987

I don't know how rebasebot works, but wouldn't it be better to checkout 2.8.2 tag https://github.com/kedacore/keda-olm-operator/tree/v2.8.2 and cherry pickhttps://github.com/kedacore/keda-olm-operator/pull/173 ?

**Comment by joelsmith** [comment]
Possibly failing due to needed changes from https://github.com/openshift/release/pull/35936

**Comment by joelsmith** [comment]
/hold
I also need to check to see if the govet will now pass with  an update of vendor deps

**Comment by joelsmith** [comment]
> audit log feature is missing, is that intentional? [kedacore@1f91a80](https://github.com/kedacore/keda-olm-operator/commit/1f91a80bc8d54206a23c5ffc9fb6b9457abff987)
> 
> I don't know how rebasebot works, but wouldn't it be better to checkout 2.8.2 tag https://github.com/kedacore/keda-olm-operator/tree/v2.8.2 and cherry pickhttps://github.com/[kedacore/pull/173](https://github.com/kedacore/keda-olm-operator/pull/173) ?

The result we want is functionally similar to what you describe, but rebasebot gives us two essential features:
* A proper merge of our modified downstream version with the upstream version
* Management of the openshift-specific `UPSTREAM:` commits which allows us to carry the changes we make from the upstream version (and drop them when appropriate) without losing track of them or ending up with a jumbled mess.

**Review by zroubalik — APPROVED** [review]
LGTM

**Review by zroubalik — APPROVED** [review]
/lgtm

**Pull request merged**
