### PR TITLE
Upstream rebase to 2.12.1

### PR DESCRIPTION
**Pull request by joelsmith**
1. Run rebasebot
```
rebasebot --source https://github.com/kedacore/keda-olm-operator:main \
          --dest openshift/custom-metrics-autoscaler-operator:main \
          --rebase joelsmith/keda-olm-operator:rebase --tag-policy=strict --update-go-modules --dry-run \
          --github-user-token <(yaml2json ~/.config/hub | jq -r '."github.com"[0].oauth_token')
```
2. Squash `UPSTREAM: <carry>: add generated CMA CSV files for 2.11.2` parts 1 to 5 and `UPSTREAM: <carry>: add generated CMA CSV files for 2.7.1-2.10.1` into new `UPSTREAM: <carry>: add generated CMA CSV files for 2.7.1-2.11.2`
3. Squash `UPSTREAM: <carry>: Generate/check CMA CSV files` parts 1 to 4
4. Update `OWNERS` file and squash update into `UPSTREAM: <carry>: Add OpenShift OWNERS file`
5. Add new carry patches `add generated CMA CSV files for 2.12.1` and `Update container base images`
6. Cherry-pick https://github.com/kedacore/keda-olm-operator/pull/221

### CODE REVIEW

**Comment by joelsmith** [comment]
/hold
Trying to figure out whether CRO is FIPS compliant or not

**Comment by joelsmith** [comment]
/hold cancel
wrong PR

**Comment by joelsmith** [comment]
Let's see if https://github.com/openshift/release/pull/49697 makes it so we can see why the e2e is failing on this PR.
/retest

**Comment by joelsmith** [comment]
The operator is failing to run:
```
/manager: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by /manager)
/manager: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by /manager)
```

Are we building with one version of glibc then moving the binary to a base image with a different version? I will investigate.

**Comment by joelsmith** [comment]
The kafka scaler tests are failing. It seems like the kafka CRD isn't on the cluster when the test runs. Is it a flake or a change in how the tests are run which we need to replicate? I'll investigate while it runs again.

/retest

**Comment by joelsmith** [comment]
It looks like we will need https://github.com/openshift/release/pull/49783 and https://github.com/openshift/kedacore-keda/pull/23 before the test will pass here.

**Comment by joelsmith** [comment]
Fingers crossed!

/retest

**Comment by jkyros** [comment]
Looks great! Thanks for grabbing the metrics API port fix, too -- saves me some trouble! :smile: 

It looks like maybe the carry patch https://github.com/openshift/custom-metrics-autoscaler-operator/commit/d582ae5bdc89c9ee4484e56aa5da9327c5f54142  (add .ci-operator.yaml) can be completely squashed with/superseded by https://github.com/openshift/custom-metrics-autoscaler-operator/commit/4823c83b7a26c36a0d76e0916f56bed8e3a3f5fb (Update container base images) but I'm not the police, and I don't think the juice is worth the squeeze now.  Maybe next time. 

/lgtm

**Pull request merged**
