### PR TITLE
PODAUTO-228: Upstream rebase to 2.15.1

### PR DESCRIPTION
**Pull request by jkyros**
1. Run rebasebot:
```
rebasebot --source https://github.com/kedacore/keda-olm-operator:main \  
--dest openshift/custom-metrics-autoscaler-operator:main \
 --rebase jkyros/custom-metrics-autoscaler-operator:rebase-2.15 --tag-policy=strict \ 
--update-go-modules --dry-run  --github-user-token ~/githubtoken
```
2. Squash CSV commits together
3. Add CSV commits for both 2.15.0 and 2.15.1
4. Left container base image on registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.17, will move to 4.18 if we think we want to ?

### CODE REVIEW

**Comment by jkyros** [comment]
We need https://github.com/openshift/kedacore-keda/pull/35 first, then we should be able to come back here and the tests should pass. It's using the "old" test container right now.

**Comment by joelsmith** [comment]
/lgtm
I do prefer to use the 4.17 base image since it has been released, so that is good as-is. Hopefully the E2E will pass once the operand rebase merges.

**Comment by joelsmith** [comment]
Let's see if the E2E passes now that the operand is merged.
/retest

**Comment by jkyros** [comment]
/retest
```
[36mINFO[0m[2024-11-08T20:31:32Z] Ran for 44m24s                               
[31mERRO[0m[2024-11-08T20:31:32Z] Some steps failed:                           
[31mERRO[0m[2024-11-08T20:31:32Z] 
  * could not run steps: step cma-e2e-aws-ovn failed: failed to acquire lease for "aws-quota-slice": status 502 Bad Gateway, status code 502 
[36mINFO[0m[2024-11-08T20:31:32Z] Reporting job state 'failed' with reason 'executing_graph:step_failed:utilizing_lease:acquiring_lease' 
```

**Comment by jkyros** [comment]
Hmm, it's still running the old test. The new test container was promoted at 19:52Z and the test run didn't start until 20:37Z so it should have had it...but it didn't. 

The 2.15.1 code definitely [doesn't still have azure in there](https://github.com/openshift/kedacore-keda/blob/737942edd29e6c07c73b6b12e393fdac72a7b961/tests/internals/trigger_authentication_validation/trigger_authentication_validation_test.go#L71) as the template value, but the 2.14.1 code [did](https://github.com/openshift/kedacore-keda/blob/744d0122d8f4f869cb7df223b7d13ec3cbd89f32/tests/internals/trigger_authentication_validation/trigger_authentication_validation_test.go#L80). 

That's totally what we're hitting here: 
```
 helper.go:633: Applying template: triggerAuthNilITemplate
    helper.go:655: 
        	Error Trace:	/src/tests/helper/helper.go:655
        	            				/src/tests/internals/trigger_authentication_validation/trigger_authentication_validation_test.go:188
        	            				/src/tests/internals/trigger_authentication_validation/trigger_authentication_validation_test.go:150
        	Error:      	Received unexpected error:
        	            	The TriggerAuthentication "trigger-authentication-validation-test-ta-nil" is invalid: spec.podIdentity.provider: Unsupported value: "azure": supported values: "azure-workload", "gcp", "aws", "aws-eks", "none"
        	Test:       	TestScaler
        	Messages:   	cannot apply file - The TriggerAuthentication "trigger-authentication-validation-test-ta-nil" is invalid: spec.podIdentity.provider: Unsupported value: "azure": supported values: "azure-workload", "gcp", "aws", "aws-eks", "none"
    helper.go:633: Applying template: triggerAuthWorkloadNilITemplate
```

**Comment by jkyros** [comment]
```
[36mINFO[0m[2024-11-09T02:21:46Z] Ran for 2h53m22s                             
[31mERRO[0m[2024-11-09T02:21:46Z] Some steps failed:                           
[31mERRO[0m[2024-11-09T02:21:46Z] 
  * could not run steps: step cma-e2e-aws-ovn failed: "cma-e2e-aws-ovn" test steps failed: "cma-e2e-aws-ovn" pod "cma-e2e-aws-ovn-test-run" failed: could not watch pod: the pod ci-op-687q19mv/cma-e2e-aws-ovn-test-run failed after 1h22m11s (failed containers: test): ContainerFailed one or more containers exited

Container test exited with code 2, reason Error
```
what is even going on tonight, wow. 
/retest

**Comment by jkyros** [comment]
Alright, that's super weird. It looks like we successfully run the prometheus tests but then we somehow fail after 5 loops of waiting for the namespace to be deleted. And we have plenty of time left as far as I can tell, so I don't think we're timing out. 

```
    helper.go:359: waiting for namespace prometheus-metrics-test-ns deletion
    helper.go:359: waiting for namespace prometheus-metrics-test-ns deletion
    helper.go:359: waiting for namespace prometheus-metrics-test-ns deletion
    helper.go:359: waiting for namespace prometheus-metrics-test-ns deletion
    helper.go:359: waiting for namespace prometheus-metrics-test-ns deletion
--- FAIL: TestPrometheusMetrics (238.95s)
FAIL
FAIL	github.com/kedacore/keda/v2/tests/sequential/prometheus_metrics	238.962s
FAIL
```
EDIT: nope, it's actually this failure here: 
```
    prometheus_metrics_test.go:1448: --- testing cloudevent emitted ---
    helper.go:703: Deleting template: scaledObjectTemplate
    helper.go:626: Applying template: cloudEventSourceTemplate
    helper.go:626: Applying template: scaledObjectTemplate
    prometheus_metrics_test.go:1472: metric not available <--- this is a t.Errorf(), the test continues after, but it still fails the test (yay! that's not confusing at all!) 
```
But it didn't fail in the operand tests, so the install part of `setup_test.go` must do something with event sources? That the bundle install here doesn't do?

**Pull request merged**
